version: '3.8'
services:
  api2:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - crudmysql
    environment:
      - DB_HOST=crudmysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=Jaqueline
  crudmysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=Jaqueline
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: